creator/urls.py
from django.contrib import admin
from django.urls import path

from creator.views import Home, CreateCv

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('createdoc', CreateCv.as_view(), name='createdoc')
]

creatucv/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('creator.urls', 'creator'), namespace='creator'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

creator/models.py
from django.db import models


class Curriculum(models.Model):
    name = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='photos')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Document(models.Model):
    file = models.FileField(upload_to='cvs')
    nickname = models.CharField(max_length=250)
    url = models.CharField(max_length=250)
    ip = models.GenericIPAddressField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

creator/views.py
import os

import requests
from django.conf import settings
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.template import loader
from django.views import View

from creator.models import Document
from creator.render import Render


class Home(View):
    template_name = 'creator/home.html'

    def get(self, *args, **kwargs):
        return render(self.request, self.template_name, {})


class CreateCv(View):
    def post(self, *args, **kwargs):
        nickname = self.request.POST.get('nickname', '')
        url = 'https://bio.torre.co/api/bios/{}'.format(nickname.strip())
        if not nickname:
            return JsonResponse({'message': 'Ingrese un nickname'}, status=202)
        try:
            resp = requests.get(url)
            file = Render.render(nickname, resp)
            data = {
                'nickname': nickname,
                'file': 'cvs/%s' % file[0],
                'url': str(resp.url),
                'ip': get_client_ip(self.request)
            }
            doc = Document.objects.create(**data)
            t = loader.get_template('creator/render.html')
            renderhtml = t.render({'document': doc})
            return JsonResponse({'renderhtml': renderhtml}, status=200)
        except ConnectionError:
            return JsonResponse({'message': 'Error al conectar con el api'}, status=500)


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/creator/home.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Crea tu cv</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'creator/css/creator.css' %}">
</head>

<body>

<div id="loading" class="processing">
    <span>Procesando...</span>
</div>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Crea tu cv</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col text-center pt-5">
            <div class="card m-auto p-5">
                <h1>Crea tu cv</h1>
            <form id="formCreateDoc" action="{% url 'creator:createdoc' %}" method="post"> {% csrf_token %}
                <label for="nickname"> Ingresa tu nickname (lorep19)</label>
                <input class="form-control col-md-4 m-auto" type="text" id="nickname" name="nickname" placeholder="Ingresa tu nickname">
                <button class="btn btn-primary m-5" id="btnSubmit">Crear Cv</button>
            </form>

            <div id="response">

            </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'creator/js/main.js' %}"></script>
</body>

</html>

templates/creator/render.html
<div class="card">
  <div class="card-body">
      <a href="{{ document.file.url }}" download>Descargar Archivo</a>
  </div>
</div>